### ISSUE TITLE
Does it sync the whole srt file...

### ISSUE THREAD

**Issue by pawamoy** [smacke/subsync#1]
...or just put an offset at the beginning?

I mean, if the subtitles start right, but then get delayed in the middle of the sequence (like +200ms), will it be fixed / resynchronized?

**Comment by smacke** [comment]
Unfortunately, right now that functionality isn't implemented. The assumption is that the unsynchronized subtitles have the same rigid time offset everywhere. That said, if you use VLC as your media player, you can perform one-off adjustment in 50ms increments with the "h" and "j" hotkeys.

**Comment by pawamoy** [comment]
Yes I know about this feature in VLC, would have been nice to be able to fix these wrong timings once and for all :slightly_smiling:

**Comment by quentinus95** [comment]
@smacke do you plan to implement this feature?

**Comment by smacke** [comment]
@quentinus95 I plan to try when I have the cycles. I'm optimistic that it can be done, but I think it's a considerably more difficult problem that starts to cross into research territory, so I unfortunately can't make any promises.
