### ISSUE TITLE
Specify start time for processing?

### ISSUE THREAD

**Issue by schmitmd** [smacke/subsync#20]
It seems to me that if there's an introduction sequence to the video (theme song, etc), subsync keys off of audio for that and moves the sub timing too early.  
Feature request here: Add an option to have subsync start its analysis at/after a specific timestamp?

**Comment by smacke** [comment]
Hi there,

That could work, but the algorithm should theoretically be robust to this case, which makes me think there might be another solution. I'll definitely implement the requested functionality, but would you mind also sharing the output you get, as well as a ballpark figure for what the correct offset should be?

**Comment by schmitmd** [comment]
Examined a bit more closely and I see what happened.  Seems the conversion split off the first few items due to the overall shift amout and that's what resulted in the off-sync.  Did I find an edge case?
```
./.local/bin/subsync 1x01.Flushed.mkv  -i 1x01.Flushed.en.srt -o 1x01.Flushed.en.srt-synced
INFO:subsync.subsync:extracting speech segments...
100%|#####################################################################################################| 1757.568/1757.568 [00:14<00:00, 107.44it/s]
INFO:subsync.subsync:...done.
INFO:subsync.subsync:computing alignments...
INFO:subsync.subsync:...done.
INFO:subsync.subsync:auditok: (108287.00000000001, -1140)
INFO:subsync.subsync:webrtcvad: (37706.0, -137)
INFO:subsync.subsync:offset seconds: -11.400
WARNING:srt:Skipped subtitle at index 1: Start time < 0 seconds
WARNING:srt:Skipped subtitle at index 2: Start time < 0 seconds```

**Comment by schmitmd** [comment]
Think I found the issue.  The subs are correct but for the one at index 2 being about a second too late.  Possibly more important, the initial parts of the srt cover the intro and look like this (I'm betting the music symbols are to blame):
```
1
00:00:01,968 --> 00:00:04,734
♪

2
00:00:09,434 --> 00:00:12,767
♪ you won't admit you love me ♪

3
00:00:12,767 --> 00:00:14,534
♪ and so ♪

4
00:00:14,534 --> 00:00:17,234
♪ how am i ever ♪

5
00:00:17,234 --> 00:00:19,033
♪ to know ♪

6
00:00:19,033 --> 00:00:21,667
♪ you always tell me ♪

7
00:00:21,667 --> 00:00:25,133
♪ perhaps, perhaps, perhaps ♪

8
00:00:26,200 --> 00:00:28,267
♪ perhaps ♪

9
00:00:28,267 --> 00:00:30,601
♪ perhaps ♪

10
00:00:30,601 --> 00:00:32,133
♪ perhaps ♪

11
00:00:35,400 --> 00:00:37,334
So you're really
going to do it?
```

**Comment by smacke** [comment]
> The subs are correct but for the one at index 2 being about a second too late.

By this, do you mean that just the 2nd sub is 1 second too late, or all subs >= 2 are ~1 second too late?

By the way: in your case, it looks like auditok is misbehaving -- if we had used the offset from webrtcvad here, it should have given a good (or at least better) offset than -11.4 seconds. I'm in the process of developing a more comprehensive suite of integration and ETE tests, but at this point I think it's safe to get rid of auditok, which is next on my todo list.

**Comment by schmitmd** [comment]
Sorry for the lack of clarity.  I did indeed mean that all subs >= 2 are ~1 second too late.

**Comment by smacke** [comment]
Gotcha. This is definitely an issue I've seen before then, whereby auditok is getting higher-scoring alignments by virtue of having higher recall than webrtc's VAD, even though the alignments are crappy. I have a fix that I will push out tomorrow; will let you know once it's available.

**Comment by smacke** [comment]
@schmitmd The latest version should behave better on your inputs; if you grab it via `pip install git+https://github.com/smacke/subsync` you should see your problem go away (please let me know if not).

I still think it would be useful to allow users to specify a start time to begin processing, so I'll leave this open as an enhancement.

**Comment by schmitmd** [comment]
That worked like a _**charm**_.  Brilliant, you are.

**Comment by smacke** [comment]
Great! Glad it worked.
