### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by mabushey** [smacke/subsync#22]
This is awesome! Can't wait to have it running.

```
$ python -V
Python 2.7.15+

$ pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

$ pip install git+https://github.com/smacke/subsync
Collecting git+https://github.com/smacke/subsync
  Cloning https://github.com/smacke/subsync to /tmp/pip-knBFFV-build
Collecting argparse (from subsync==0.2.0)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting ffmpeg-python (from subsync==0.2.0)
  Using cached https://files.pythonhosted.org/packages/d0/76/d04cf269e20bbb0357d2641e20a4d8b9e1bec7cb8485389a001a6ace6018/ffmpeg_python-0.1.17-py2-none-any.whl
Collecting future (from subsync==0.2.0)
Collecting numpy>=1.12.0 (from subsync==0.2.0)
  Using cached https://files.pythonhosted.org/packages/c4/33/8ec8dcdb4ede5d453047bbdbd01916dbaccdb63e98bba60989718f5f0876/numpy-1.16.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting srt (from subsync==0.2.0)
Collecting tqdm (from subsync==0.2.0)
  Using cached https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl
Collecting webrtcvad (from subsync==0.2.0)
Installing collected packages: argparse, future, ffmpeg-python, numpy, srt, tqdm, webrtcvad, subsync
  Running setup.py install for subsync ... done
Successfully installed argparse-1.4.0 ffmpeg-python-0.1.17 future-0.17.1 numpy-1.16.2 srt-1.10.0 subsync-0.2.0 tqdm-4.31.1 webrtcvad-2.0.10
```

My opinion of pip (and every other poor implementation of apt) is it's only useful for Docker containers or while working on the code.  On a system it's idiotic to have to run pip install --upgrade, npm update, composer update, etc to upgrade. I run `Debian`, it uses `apt`. Once I figure out how to run this utility I'll Dockerize it so I won't have to deal with this down the road and save others the headache known as pip. I'm running guessit (utility that downloads subtitles) in a docker container, utilities like this are awesome in Docker.

```
$ pip show subsync                                                                                                                                                                                              
Name: subsync
Version: 0.2.0
Summary: Language-agnostic synchronization of subtitles with video via speech detection.
Home-page: https://github.com/smacke/subsync
Author: Stephen Macke
Author-email: stephen.macke@gmail.com
License: MIT
Location: /home/michael/.local/lib/python2.7/site-packages
Requires: argparse, ffmpeg-python, future, numpy, srt, tqdm, webrtcvad
```
Looks like I can install some of them the right way:
```
$ sudo apt-get install python-future
$ sudo apt-get install python-numpy
$ sudo apt-get install python-tqdm
```

```
$ ls -al /home/michael/.local/lib/python2.7/site-packages/subsync/subsync.py
-rw-rw-r-- 1 michael michael 6104 Mar  7 18:42 /home/michael/.local/lib/python2.7/site-packages/subsync/subsync.py

$ /home/michael/.local/lib/python2.7/site-packages/subsync/subsync.py
zsh: permission denied: /home/michael/.local/lib/python2.7/site-packages/subsync/subsync.py

$ chmod 764 /home/michael/.local/lib/python2.7/site-packages/subsync/subsync.py

$ /home/michael/.local/lib/python2.7/site-packages/subsync/subsync.py
Traceback (most recent call last):
  File "/home/michael/.local/lib/python2.7/site-packages/subsync/subsync.py", line 13, in <module>
    from .utils import read_srt_from_file, write_srt_to_file, srt_offset
ValueError: Attempted relative import in non-package
```

No idea how to run it...

**Comment by mabushey** [comment]
Ugg I just read #1, this utility isn't what I thought it was. :(  Subslider.py already does this good enough. syncing continuously is what I was looking for.

**Comment by smacke** [comment]
Hi, when you did the initial pip install, it already grabbed all the dependencies; there's no need to look for them manually via apt.

It should have installed a `subsync` executable in `/home/michael/.local/bin`; if you decide you want to try this out after all, then if you use that one you should see that error go away.

**Comment by mabushey** [comment]
Thanks @smacke you're right. Since it's installed I'll play with it. I wish it could sync every line!

**Comment by smacke** [comment]
@mabushey me too :) this problem is a lot more challenging, but I want to handle this kind of thing in a robust manner once I have a good set of test cases against which to try out different algorithms.

**Comment by mabushey** [comment]
@smacke I'm not much on python (php/bash coder), but if there's anything related to testing or the like I can do to help let me know.

**Comment by smacke** [comment]
@mabushey thanks for offering! if you happen to run across any free movies or TV episodes that have out-of-sync subs where the problem points happen in the middle (e.g. due to one or more commercial breaks), I definitely appreciate any pointers as these would make great test cases.
