### ISSUE TITLE
Subsync won't keep original subtitle encoding on synchronized one

### ISSUE THREAD

**Issue by javad94** [smacke/subsync#23]
Hi, Thanks for this interesting command line tool. There is one bug that makes a problem when using this tool on languages like Persian. When synchronizing Persian subtitle, it doesn't preserve encoding of the original file, which make the synchronized subtitle unusable.
 
<img width="552" alt="cmd_2019-03-08_15-34-49" src="https://user-images.githubusercontent.com/7765309/54027802-fa8ee480-41b7-11e9-9a3d-bd89816e80c6.png">

**Comment by smacke** [comment]
Hi there,

Thanks for bringing this to my attention. With the latest changes in 38fda02884b1583b35a42e3b9633315b6c7b5a16, the input encoding should be preserved in the output. Additionally, you can manually specify the input encoding using the --encoding flag (by default it tries to infer from a fixed set).

If you grab the latest via `pip install git+https://github.com/smacke/subsync`, it should be fixed.

Please let me know if this doesn't fix your particular case and I'll try further; supporting as many languages as possible is a priority.

Best,
Stephen

**Comment by javad94** [comment]
Great, thank you. It's work as expected now.

**Comment by smacke** [comment]
Awesome! Thanks for letting me know.
