### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Koxx3** [smacke/subsync#25]

**Comment by smacke** [comment]
Hi, this isn't much to go off. Could you share how you are running the command and copy the full stack trace?

**Comment by Koxx3** [comment]
Hi,
lol ... I tried to cancel the ticket, but it seems I didn't manage to do it ;)
Don't worry, it's just that I didn't have ffmped installed ...
everything is working fine on my debian.
wonderful application. thanks a lot !

**Comment by smacke** [comment]
Gotcha, glad it is useful!
