### ISSUE TITLE
Measuring FFT process time

### ISSUE THREAD

**Issue by sgh7398** [smacke/subsync#26]
I am interested in calculating the time of FFT process. I tried to add datetime function before and after the FFT calculations in the aligners.py file and printing out the time, before the installation. However, when I installed it didn't work out. I was wondering how i can do some modifications to your code (like this issue that I mentioned) before the installation.

Thanks very much

**Comment by smacke** [comment]
Hi there,

My guess is that you need to bump the version in order for the installation to pick up your changes. Try increasing the value in [https://github.com/smacke/subsync/blob/master/subsync/version.py](version.py) locally, and then running `pip install .`. Hopefully it should pick up your changes; please let me know if not.
