### ISSUE TITLE
Does it support other languages rather than English?

### ISSUE THREAD

**Issue by JafarAkhondali** [smacke/subsync#3]
Does it support other languages rather than English?
Nothing is mentioned in the read.me.
If it currently does not support other languages, is there a guide line to develop it for others?

**Comment by HazCod** [comment]
I think it does, since it detects any voice audio appearing and the srt timing. @smacke ?

**Comment by alladinian** [comment]
It would be surprising if it didn't since the very first line of the readme states:
> Language-agnostic automatic synchronization of subtitles to video...

**Comment by smacke** [comment]
Yes! So far I've tested on English and Mandarin and it seems to work fine. Since it's just using presence / absence of speech, I think it should work for any language.
