### ISSUE TITLE
Accept music files (mp3, wav, ogg)

### ISSUE THREAD

**Issue by Kimonode** [smacke/subsync#40]
I am using SubSync to sync lyrics with mp3 files. But to do so, I have to convert the mp3 files to wmv format, just to be compatible with the format requirement.

Since the README states that "the most expensive step is actually extraction of raw audio", having an option to load raw music files instead of movie files would be a nice improvement in terms of performance and ergonomy.

**Comment by smacke** [comment]
Hi there, thanks for opening an issue. That's interesting -- I would have expected it should work with just the mp3, since ffmpeg should recognize that. Did you try using the mp3 directly? If so, what was the error you got?

**Comment by smacke** [comment]
I see -- partially the comment was about efficiency. Even for audio formats like mp3 we still need to extract a raw wav, so I don't see a way around this. Since it already works with audio files thanks to ffmpeg I'm going to go ahead and close this.
