### ISSUE TITLE
Are you planning to expand to cover foreign languages?

### ISSUE THREAD

**Issue by andrep182** [smacke/subsync#41]
Hi,

Not sure if this is the right place to ask this as this isn't a bug. Are you planning to expand to cover foreign movies other than English spoken ones? I tried using this tool to sync up some of my Korean movies subtitles, but got the error for not having the dictionary for it. So, just wondering if this is something that you would be covering or not in the future, thanks.

**Comment by smacke** [comment]
Hi @andrep182, I think you probably installed another library -- unfortunately the official subsync on PyPi is different from this one. Try grabbing this one via
```
pip install git+https://github.com:smacke/subsync
```
The library I wrote doesn't do any transcription, just voice detection, so it should work cross-languages.
