### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by loveisalie92** [smacke/subsync#44]
Hi,
Sorry as i don't familiar with Python.
I try to install the package using "pip install git+https://github.com/smacke/subsync" but i'm not able to run the sync command, for example: "subsync video.mp4 -i unsynchronized.srt > synchronized.srt".

The system suggest me to install a package with the same name "subsync" using snap but i guess that not your package.(I'm using ubuntu 18.04)

Please help!

**Comment by LosEagle** [comment]
How did you resolve this issue?
