### ISSUE TITLE
Issue on Windows x64

### ISSUE THREAD

**Issue by 1boko1** [smacke/subsync#47]
The "fcntl" module doesn't exist  !

from .speech_transformers import SubtitleSpeechTransformer, VideoSpeechTransformer
  File "c:\users\avign\appdata\local\programs\python\python37-32\lib\site-packages\subsync\speech_transformers.py", line 2, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Comment by smacke** [comment]
Thanks for filing an issue. Forgot that fcntl is *nix only. Fix coming in next ~1 minute.

**Comment by smacke** [comment]
If you reinstall (`pip install --upgrade git+https://github.com/smacke/subsync`) the issue should go away.

**Comment by 1boko1** [comment]
Yes, thanks. It's working now.
