### ISSUE TITLE
Have you considered the Mozilla Public License v2 instead of LGPL?

### ISSUE THREAD

**Issue by naltun** [smacke/subsync#5]
https://github.com/smacke/subsync/blob/42f95e652451ce29f24c9d75ddc78ad37f26359d/setup.py#L28

If you are struggling with choosing a balanced FOSS license, you may want to consider the Mozilla Public License v2.0.

Look [here](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) for the MPLv2.0 FAQs.

**Comment by smacke** [comment]
Thanks for catching this -- actually this project was already MIT licensed, and I had forgotten to update it in setuptools.

**Comment by naltun** [comment]
Great project. Good job, and good luck.

**Comment by smacke** [comment]
Thank you!!!
