### ISSUE TITLE
Danish dialogue support + "basic mode" feature request

### ISSUE THREAD

**Issue by wellloaded** [smacke/subsync#52]
First of all thank you for this awesome software, it's genius!

I noticed that currently the spoken Danish is not supported so I was wondering if there's any plan to support this. Also I like a lot the option to synchronise subtitles with subtitles instead of video. Often movies come with strange subtitles format and OCR them is not easy/quick/simple so download a plain .srt version from Internet and using subsync is a wonderful function to have! Well done.

Beside this I have a minor feature request:

assuming the source subtitle file is simply offset compared to the dialog in the video file (great majority of the cases unless it's a re-edited/remasters/director-cut version), could SubSync have a "basic mode" where instead of trying to understand what the dialog says it would just try to match "voice" with "text"? This could be the default action if the audio language is left to "Unknown"...

Regardless many thanks for the fantastic software!!

**Comment by smacke** [comment]
Hi! I think you might have this subsync confused with one of the (many other) "subsyncs" out there. This one does exactly what you suggest and matches voice with text, and shouldn't care about the language of either.

Note: the subsync on PyPI that you get from `pip install subsync` is *not* this one; I'm still thinking of a good name for PyPI. In the meantime, it's installed via `pip install git+https://github.com/smacke/subsync@STABLE`
