### ISSUE TITLE
use cchardet to autodetect text encodings

### ISSUE THREAD

**Issue by smacke** [smacke/subsync#54]
ref: https://github.com/PyYoshi/cChardet

While we're at it, it probably makes sense to change the default output encoding to utf-8, since this seems to be what players like VLC expect.

**Comment by sfkpmr** [comment]
Would this solve issues where currently Swedish å is written as "├Ñ", ä as "├ñ" and ö as "├╢"?

**Comment by smacke** [comment]
Hi @sfkpmr, I believe this would solve this issue but it's hard to say for sure. Do you have a test file that I could use to verify with by any chance?

**Comment by sfkpmr** [comment]
Sure > https://pastebin.com/BVzA1eLD

**Comment by smacke** [comment]
Thank you @sfkpmr! Actually what you posted looks like utf-8, which should be handled correctly by most software (including subsync). What are the circumstances under which you see the malformed characters?

**Comment by sfkpmr** [comment]
I simply ran per the instructions, subsync video.mp4 -i unsynchronized.srt > synchronized.srt, and the output looks like this:

https://pastebin.com/2M3Q8z3e

**Comment by smacke** [comment]
@sfkpmr gotcha. I'm having trouble reproducing this -- what version are you running? You can find out by running `subsync --version`

**Comment by smacke** [comment]
@sfkpmr actually I have a different hypothesis as to what is going on -- probably the original srt file you have is not encoded in utf8, but my guess is that it gets converted to utf8 on your system clipboard when you copy the contents of the file and paste to pastebin. If so, sorry for the wild goose chase -- I'm guessing I would need the original file (not copied+pasted to pastebin) in order to figure out whether this is an encoding issue as I suspect.

**Comment by sfkpmr** [comment]
That's odd, Windows' save dialog suggests that it is using UTF-8.

I uploaded the file [here](https://we.tl/t-7t3mMpkEsL).

**Comment by smacke** [comment]
@sfkpmr thank you so much for continuing to help troubleshoot this. As you said, it is UTF-8, so something else must be going on.

In the most recent release of subsync (which can be installed via `pip install --upgrade git+https://github.com/smacke/subsync@STABLE`), there is a flag `--make-test-case` which creates a compressed archive of all files involved for help with later debugging. (It simply fingerprints the movie to avoid copyright issues.) Example usage is:

`subsync reference.mp4 -i unsynced.srt -o synced.srt --make-test-case`

and it will create a file `reference.mp4.tar.gz`.

Would you be willing to do this for me and upload the tarball so I can take a closer look at what's going on?

Also, it's possible that the latest version doesn't have this issue anymore.

**Comment by smacke** [comment]
Hi @sfkpmr I'm going to go ahead and close this issue since I don't seem to see the encoding corruption issues with the latest version when running your test file. Please feel free to reopen if the latest v doesn't fix your issue (can grab with `pip install --upgrade git+https://github.com/smacke/subsync@STABLE`).
