### ISSUE TITLE
install failed: permission denied on got submodule

### ISSUE THREAD

**Issue by svenjochems** [smacke/subsync#56]
Submodule https://github.com/smacke/subsync-data is not accessible causing pip install to fail.

Collecting git+https://github.com/smacke/subsync@STABLE
  Cloning https://github.com/smacke/subsync (to revision STABLE) to /tmp/pip-req-build-dy_ijyxx
  Running command git clone -q https://github.com/smacke/subsync /tmp/pip-req-build-dy_ijyxx
  Running command git submodule update --init --recursive -q
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  fatal: clone of 'git@github.com:smacke/subsync-data' into submodule path '/tmp/pip-req-build-dy_ijyxx/test-data' failed
  Failed to clone 'test-data'. Retry scheduled
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  fatal: clone of 'git@github.com:smacke/subsync-data' into submodule path '/tmp/pip-req-build-dy_ijyxx/test-data' failed
  Failed to clone 'test-data' a second time, aborting
ERROR: Command errored out with exit status 1: git submodule update --init --recursive -q Check the logs for full command output.

**Comment by smacke** [comment]
@svenjochems thank you for filing this issue. The submodule is a private repo containing data for the integration tests; I didn't realize pip would try to grab it. Dang... another reason why #55 and #36 need to happen asap.

For now I went ahead and did a quick fix. If you repeat the command it should work, but change the all-caps STABLE to stable as follows:

`pip install git+https://github.com/smacke/subsync@stable`
