### ISSUE TITLE
Build subsync on FreeBSD

### ISSUE THREAD

**Issue by Zamana** [smacke/subsync#57]
Hi!

Does anybody tried to build subsync on FreeBSD?

I'm trying but there are a lots of errors because pip can't install a lot of packages:

Building wheel for scipy (PEP 517) ... error
Building wheel for scikit-learn (setup.py) ... error

It's a FreeBSD 11.3-RELEASE.

Thanks.
Regards.

**Comment by smacke** [comment]
Hi @Zamana,

Hmm, those packages (scipy and scikit-learn) are pretty essential Python packages -- maybe file an issue for them? I could potentially try to help if those error messages were expanded, but I would focus on figuring out what fails when trying to install packages like numpy / scipy / scikit-learn before trying to install subsync. E.g. I recommend making sure the following works first:
```
pip install numpy scipy scikit-learn
```

**Comment by Zamana** [comment]
Hi!

Thanks for the instructions. They SOLVED the problem.

And the problem is that another package was missing: **Cython**.

After installing Cython and completing the numpy, scypi and scikit-learn installation, I was able to install subsync successfully by following the instructions.

Thank you very much!
Best regards.

**Comment by smacke** [comment]
Hi! Glad you were able to troubleshoot the issue -- I'm afraid I still don't understand what's going on (if Cython is a dependency of one of those other packages, shouldn't it have been grabbed automatically by pip?) but glad it's resolved regardless.

**Comment by sindreruud** [comment]
Just to add onto this if anyone else stumbles across it. I'm running FreeNAS 11.3 and tried installing this in a iocage jail (FreeBSD) with py37. 

`pip install git+https://github.com/smacke/subsync@stable`

Did not work for me and like Zamana it spit out a bunch of errors. Here is a snippet of the error:
```
Collecting scipy>=0.17.0 (from scikit-learn>=0.20.4->subsync==0.3.4)
  Downloading https://files.pythonhosted.org/packages/04/ab/e2eb3e3f90b9363040a3d885ccc5c79fe20c5b8a3caa8fe3bf47ff653260/scipy-1.4.1.tar.gz (24.6MB)
     |████████████████████████████████| 24.6MB 1.4MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Complete output from command /usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpqx61796d:
    ERROR: lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
    C compiler: cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC
```

And there is a bunch of others aswell. So i tried installing cython as suggested, aswell as installing numpy scipy and scikit-learn.

`pip install numpy` went fine, but both scipy and scikit-learn gave me errors. So i did some googling and realized there are port / package for scipy. Read more here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236909

So I installed it:
`pkg install py37-scipy `
And for reference it installs these other dependencies:
```
binutils: 2.33.1_2,1
gcc9: 9.3.0
metis: 5.1.0_8
mpc: 1.1.0_2
mpfr: 4.0.2
openblas: 0.3.7_2,1
py37-numpy: 1.16.5_4,1
py37-scipy: 1.2.2_1
suitesparse: 5.4.0_6
tbb: 2020.2
```

And now running
`pip install git+https://github.com/smacke/subsync@stable`
works like a charm.

And you can verify in the terminal output that it finds the libs
```

Requirement already satisfied: scikit-learn>=0.20.4 in /usr/local/lib/python3.7/site-packages (from subsync==0.3.4) (0.22.2.post1)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.7/site-packages (from scikit-learn>=0.20.4->subsync==0.3.4) (1.2.2)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.7/site-packages (from subsync==0.3.4) (1.16.5)

```

I have tried it on one subtitle that was out of sync, and it appears to properly work and synced up my subtitle.
