### ISSUE TITLE
Unable to install using pip install

### ISSUE THREAD

**Issue by nikolicjakov** [smacke/subsync#66]
https://github.com/smacke/subsync/blob/f2115018061699600574680ce8563731b43f3070/.gitmodules#L3

Hi there!

I am trying to install subsync on alpine linux using pip install command. And i am facing the issue with submodule cloning since pip is calling `git submodule update --init --recursive` my installation fails with error this error message..

```
git@github.com: Permission denied (publickey).
   fatal: Could not read from remote repository.
   Please make sure you have the correct access rights
   and the repository exists.
   fatal: clone of 'git@github.com:smacke/subsync-data' into submodule path '/tmp/pip-req-build-p3h13tk3/test-data' failed
   Failed to clone 'test-data'. Retry scheduled
   Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
   git@github.com: Permission denied (publickey).
   fatal: Could not read from remote repository.
   Please make sure you have the correct access rights
   and the repository exists.
   fatal: clone of 'git@github.com:smacke/subsync-data' into submodule path '/tmp/pip-req-build-p3h13tk3/test-data' failed
   Failed to clone 'test-data' a second time, aborting
 ERROR: Command errored out with exit status 1: git submodule update --init --recursive -q Check the logs for full command output.
```

So could you please change protocol of submodule from SSH to HTTPS? If this would be https repo link then everything should work fine..

**Comment by nikolicjakov** [comment]
Looking into submodule subsync-data i am not sure if this repository even exists?

**Comment by nikolicjakov** [comment]
It was my mistake i was not using stable notation i am sorry. Closing this issue

**Comment by smacke** [comment]
I'm sorry for the confusion with the nonstandard PyPI package (an unfortunate workaround pending rename given that `subsync` is already taken on PyPI) and glad you were able to get it figured out!

(The reason cloning directly from `master` fails is because that branch contains the test data submodule which is private, and unfortunately pip tries to grab submodules by default.)
