### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by Nainboiteu** [smacke/subsync#9]
Hello!

After the installation I can't launch Subsync the correct way:
`$ subsync reference.srt -i unsynchronized.srt -o synchronized.srt`

So I tried from the install folder:
`$ python ~/.local/lib/python2.7/site-packages/subsync/subsync.py movie.en.srt -i movie.it.srt" -o movie.2.it.srt" `

Unfortunately I've got this error:
`Traceback (most recent call last):
  File "/home/username/.local/lib/python2.7/site-packages/subsync/subsync.py", line 16, in <module>
    from .utils import read_srt_from_file, write_srt_to_file, srt_offset
ValueError: Attempted relative import in non-package`

I'm on Ubuntu 18.04 with Python 2.7 installed.

Do you know how I can correct this error?

Thanks!

**Comment by Nainboiteu** [comment]
My bad, I was able to correct these two errors by adding `/home/username/.local/bin` to my path...

**Comment by smacke** [comment]
Glad you got it working!
